version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: manboster
    main: ./cmd/manboster/main.go
    binary: manboster
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/manboster/manboster/internal/config.BuildCommit={{.ShortCommit}}
      - -X github.com/manboster/manboster/internal/config.BuildTime={{.Date}}
      - -X github.com/manboster/manboster/internal/config.CurrentVersion={{ if .IsSnapshot }}{{ envOrDefault "CHANNEL" "snapshot" }}{{ else }}{{ envOrDefault "CHANNEL" "unknown" }}{{ end }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - riscv64
    ignore:
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_{{ if .IsSnapshot }}{{ envOrDefault "ARTIFACT_VERSION" .Version }}-{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
