package model

import (
	"github.com/manboster/manboster/spec/llm"
)

// AnthropicModels defines data from Claude Sonnet/Haiku/Opus 4.5 to now
var AnthropicModels = []llm.Model{
	{
		DisplayName:     "Claude Fable 5",
		Name:            "anthropic/claude-fable-5",
		Context:         1000000,
		MaxOutputTokens: 128000,
		InputPrice:      10,
		OutputPrice:     50,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage | llm.CapabilityFile, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Sonnet 5",
		Name:            "anthropic/claude-sonnet-5",
		Context:         1000000,
		MaxOutputTokens: 128000,
		InputPrice:      2,
		OutputPrice:     10,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage | llm.CapabilityFile, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Opus 4.8",
		Name:            "anthropic/claude-opus-4.8",
		Context:         1000000,
		MaxOutputTokens: 128000,
		InputPrice:      5,
		OutputPrice:     25,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage | llm.CapabilityFile, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Opus 4.7",
		Name:            "anthropic/claude-opus-4.7",
		Context:         1000000,
		MaxOutputTokens: 128000,
		InputPrice:      5,
		OutputPrice:     25,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Sonnet 4.6",
		Name:            "anthropic/claude-sonnet-4.6",
		Context:         1000000,
		MaxOutputTokens: 128000,
		InputPrice:      3,
		OutputPrice:     15,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Opus 4.6",
		Name:            "anthropic/claude-opus-4.6",
		Context:         1000000,
		MaxOutputTokens: 128000,
		InputPrice:      5,
		OutputPrice:     25,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Sonnet 4.5",
		Name:            "anthropic/claude-sonnet-4.5",
		Context:         1000000,
		MaxOutputTokens: 64000,
		InputPrice:      3,
		OutputPrice:     15,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage | llm.CapabilityFile, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Opus 4.5",
		Name:            "anthropic/claude-opus-4.5",
		Context:         200000,
		MaxOutputTokens: 64000,
		InputPrice:      5,
		OutputPrice:     25,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage | llm.CapabilityFile, Output: llm.CapabilityText},
	},
	{
		DisplayName:     "Claude Haiku 4.5",
		Name:            "anthropic/claude-haiku-4.5",
		Context:         200000,
		MaxOutputTokens: 64000,
		InputPrice:      1,
		OutputPrice:     5,
		Reasoning:       true,
		Capabilities:    llm.Capabilities{Input: llm.CapabilityTextAndImage, Output: llm.CapabilityText},
	},
}
