name: Nightly Build

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Check if new commits exist
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "forced to build"
            echo "should_run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          LATEST_TAG=$(git tag -l "nightly-*" --sort=-v:refname | head -n 1)
          
          if [[ -z "$LATEST_TAG" ]]; then
            echo "No nightly previously"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            TAG_COMMIT=$(git rev-list -n 1 "$LATEST_TAG")
            HEAD_COMMIT=$(git rev-parse HEAD)
          
            if [[ "$TAG_COMMIT" == "$HEAD_COMMIT" ]]; then
              echo "This commit ($HEAD_COMMIT) has been built $LATEST_TAG, skip."
              echo "should_run=false" >> $GITHUB_OUTPUT
            else
              echo "Continue"
              echo "should_run=true" >> $GITHUB_OUTPUT
            fi
          fi

  nightly-release:
    needs: check-commit
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Set current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Nightly Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NIGHTLY_TAG="nightly-${{ env.DATE }}"
          gh release create "$NIGHTLY_TAG" ./dist/*.tar.gz ./dist/*.zip ./dist/checksums.txt \
            --title "Nightly Build ($NIGHTLY_TAG)" \
            --prerelease \
            --target ${{ github.sha }} \
            --notes "The latest version of nightly build"

      - name: Delete older Nightly releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 7
          delete_tag_pattern: ^nightly-
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}